src/main/java/helloworld/HelloWorldBean.java
package helloworld;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.SessionScoped;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

@ManagedBean(name="helloWorldBean")
//@RequestScoped
@SessionScoped
public class HelloWorldBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private String name;

	public String hello() {

		System.out.println("Calling hellworld.xhtml");

		return "success";

	}

	public String getCurrentTime() {

		return new SimpleDateFormat("dd MMM yyyy:HH:mm:SS").format(new java.util.Date().getTime()); // Older version, SimpleDateFormat is not thread safe
		//return LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd MMM-yyyy HH:mm:ss"));  // Requires Java 8
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
}

src/main/java/helloworld/ResultBean.java
package helloworld;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import java.io.Serializable;

//This bean is required if you  use faces-config.xml 

@ManagedBean(name="resultBean")
@RequestScoped   //You can use @ViewScoped
public class ResultBean implements Serializable {

	private static final long serialVersionUID = 1L;

	public String result() {

		System.out.println("Inside Result Bean");
		return "success";

	}

}

src/main/webapp/helloworld.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:f="http://java.sun.com/jsf/core"
xmlns:h="http://java.sun.com/jsf/html">

<h:head>
<title>My First JSF Application</title>
</h:head>
<h:body>
		<h3>JSF Hello World Example</h3>
	<h:form>
		<h3>Now The time is <h:outputLabel> #{helloWorldBean.currentTime}</h:outputLabel></h3>
		Your Name Please?
		<h:inputText value="#{helloWorldBean.name}"></h:inputText>
		<h:commandButton value="Say Hello" action="result"></h:commandButton>
	</h:form>
</h:body>
</html>

src/main/webapp/helloworld1.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:f="http://java.sun.com/jsf/core"
xmlns:h="http://java.sun.com/jsf/html">

<h:head>
<title>My First JSF Application</title>
</h:head>
<h:body>
<h3>JSF 2.2 Hello World Example with faces-config.xml</h3>
<h:form>
<h3>Now The time is <h:outputLabel> #{helloWorldBean.currentTime}</h:outputLabel></h3>
Your Name Please?
<h:inputText value="#{helloWorldBean.name}"></h:inputText>
<h:commandButton value="Say Hello" action="#{resultBean.result}"></h:commandButton>
</h:form>
</h:body>
</html>

src/main/webapp/result.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
    	<title>JSF 2.2 Hello World </title>
    </h:head>
    <h:body bgcolor="white">
    	<h2>Hi #{helloWorldBean.name} Welcome to JSF Hello World</h2>
    	    	<h2>Now the Time is #{helloWorldBean.currentTime} Bye.</h2>

    </h:body>
</html>